
name: Manual Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g. 8.0.21)'
        required: true

jobs:
  release:
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        with:
          vs-version: '17.4'

      - name: Restore Dependencies
        run: cd src && nuget restore && cd ..

      - name: Build
        run: msbuild src\\splogparser.sln /m:1 /t:Clean,Build /p:Configuration="Release" /p:Platform="Any CPU" /nodeReuse:false

      - name: Package Build Output
        run: Compress-Archive -Path dist\\* -Destination splogparser-${{ github.event.inputs.version }}.zip
        shell: pwsh

      - name: Create Git Tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git tag v${{ github.event.inputs.version }}
          git push origin v${{ github.event.inputs.version }}

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.event.inputs.version }}
          name: splogparser v${{ github.event.inputs.version }}
          files: splogparser-${{ github.event.inputs.version }}.zip
          prerelease: false
          make_latest: true
